FROM node
LABEL maintainer="nikolai muhhin <nikolai.muhhin@gmail.com>"

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app

RUN dpkg --add-architecture i386
RUN apt-get update
RUN apt-get install -y libc6:i386 libncurses5:i386 libstdc++6:i386

RUN npm install

RUN npm install pm2@latest -g
RUN pm2 startup systemd

COPY . /usr/src/app

ENV NODE_ENV production

CMD ["pm2-runtime", "index.js"]
